name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Esto ejecuta el pipeline cuando se hace un 'push' en la rama 'main'
  pull_request:
    branches:
      - main  # Esto también ejecuta el pipeline cuando se crea un 'pull request' en la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Esto especifica que el entorno será Ubuntu

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Esto clona el código del repositorio en el runner

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Especificamos la versión de Java que queremos

      - name: Build with Maven
        run: mvn clean install  # Este comando ejecuta Maven para compilar y ejecutar las pruebas

      - name: Run Tests
        run: mvn test  # Este comando ejecuta las pruebas del proyecto
